name: Deploy
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci --force
        
      - name: Build
        run: CI=false npm run build
        
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PORTFOLIO }}
          publish_dir: ./build
        
